head/urls.py
from django.urls import path
from . import views
from django.contrib.sitemaps.views import sitemap
from .sitemaps import BrandSitemap, CarSitemap, HeadPageSitemap, PostSitemap
from head.feeds import TurboFeed


sitemaps = {'static': HeadPageSitemap, 'brand': BrandSitemap, 'cars': CarSitemap, 'post': PostSitemap}

app_name = 'head'

urlpatterns = [
    path('', views.head_page, name='head_page'),
    path('popular_video/', views.popular_list, name='popular_list'),
    path('new_video/', views.new_video_list, name='new_video_list'),
    path('autonews/', views.post_list, name='post_list'),
    path('feeds/turbo/', TurboFeed()),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<slug:brand_slug>/', views.brand_list, name='video_list_by_brand'),
    path('<slug:brand_slug>/<slug:car_slug>/', views.car_list, name='video_list_by_car'),    
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

td/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('images/', include('head.urls', namespace='head_image')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('head.urls', namespace='head')),
    path('chaining/', include('smart_selects.urls')),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain'),),
]

handler404 = 'head.views.error_404_view'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

head/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from smart_selects.db_fields import ChainedForeignKey
from PIL import Image
from taggit.managers import TaggableManager


class Brand(models.Model):
    title = models.CharField(max_length=250, verbose_name='Название бренда')
    slug = models.SlugField(max_length=250, unique=True)
    image = models.ImageField(upload_to='images/brands/', blank=True, verbose_name='Логотип бренда')
    history = models.TextField(blank=True)
    
    class Meta:
        ordering = ('title',)
        verbose_name = 'brand'
        verbose_name_plural = 'brands'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
       return reverse('head:video_list_by_brand', args=[self.slug])


class Car(models.Model):
    title = models.CharField(max_length=250, verbose_name='Модель авто')
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, related_name='cars', verbose_name='Бренд')
    slug = models.SlugField(max_length=250,unique=True)
    available = models.BooleanField(default=True, verbose_name='Показывать')

    class Meta:
        ordering = ('title',)
        verbose_name = 'Car'
        verbose_name_plural = 'Cars'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
       return reverse('head:video_list_by_car', args=[self.brand.slug, self.slug])


class CarVideo(models.Model):
    created = models.DateField(auto_now_add=True, verbose_name='Дата добавления видео на сайт')
    age = models.DateField(verbose_name='Дата выхода видео')
    title_video = models.CharField(max_length=250, verbose_name='Заголовок видео')
    id_videos = models.CharField(max_length=250, verbose_name='ID видео')
    number_of_views = models.IntegerField(verbose_name='Количество просмотров')
    image_urls = models.URLField(verbose_name='Ссылка на обложку видео')
    image_jpg = models.ImageField(upload_to='images/', null=True, blank=True, verbose_name='Обложка видео jpg')
    image_webp = models.ImageField(upload_to='images/', null=True, blank=True, verbose_name='Обложка видео webp')
    image_webp_small = models.ImageField(upload_to='images/', null=True, blank=True, verbose_name='Small Обложка видео webp')
    url = models.URLField(verbose_name='Ссылка на видео')
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, related_name='carvideos', verbose_name='Марка авто')
    car = ChainedForeignKey(Car, chained_field="brand", chained_model_field="brand", show_all=False, auto_choose=True, sort=True, verbose_name='Модель авто')
    hq = models.CharField(max_length=250, verbose_name='Размер картинки')
    available = models.BooleanField(default=True, verbose_name='Показывать')
    
    class Meta:
        ordering = ['brand']
        verbose_name = 'video'
        verbose_name_plural = 'videos'

    def __str__(self):
        return self.title_video

    def get_absolute_url(self):
       return reverse('head:carvideo_feed', args=[self.brand.slug, self.slug])


class PublishedManager(models.Manager): 
    def get_queryset(self): 
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = ( 
        ('draft', 'Draft'), 
        ('published', 'Published'), 
    ) 
    title = models.CharField(max_length=250) 
    description = models.CharField(max_length=500, default='', verbose_name='Описание статьи') 
    slug = models.SlugField(max_length=250, unique_for_date='publish') 
    body = models.TextField() 
    publish = models.DateTimeField(default=timezone.now, verbose_name="Дата публикации") 
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 
    image_jpg = models.ImageField(upload_to='images/', null=True, blank=True, verbose_name='Обложка статьи jpg')
    image_webp = models.ImageField(upload_to='images/', null=True, blank=True, verbose_name='Обложка статьи webp')
    image_webp_small = models.ImageField(upload_to='images/', null=True, blank=True, verbose_name='Small Обложка статьи webp')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='published', verbose_name='Статус') 
    brand = models.ForeignKey(Brand, null=True, blank=True, on_delete=models.CASCADE, related_name='videos', verbose_name='Марка авто')
    objects = models.Manager() # The default manager. 
    published = PublishedManager() # Our custom manager.
    tags = TaggableManager(blank=True)

    class Meta: 
        ordering = ('-publish',) 

    def __str__(self): 
        return self.title

    def get_absolute_url(self):
        return reverse('head:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.slug])


class Comment(models.Model): 
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments', verbose_name='Название статьи')
    name = models.CharField(max_length=80, verbose_name='Ваше имя') 
    email = models.EmailField(verbose_name='Ваш e-mail') 
    body = models.TextField(verbose_name='Комментарий') 
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 
    active = models.BooleanField(default=True) 
 
    class Meta: 
        ordering = ('created',) 
 
    def __str__(self): 
        return 'Comment by {} on {}'.format(self.name, self.post)

head/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, label="Ваше имя")
    email = forms.EmailField(label="Ваш e-mail")
    to = forms.EmailField(label="Кому e-mail")
    comments = forms.CharField(required=False, widget=forms.Textarea, label="Комментарии")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

head/views.py
from django.shortcuts import render, get_object_or_404
from .models import Brand, Car, CarVideo, Post, Comment
from datetime import datetime
#from .mixins import findyoutube, save_video
#from .parser_news import parse_posts
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from taggit.models import Tag
from django.db.models import Count
from django.views.generic import ListView
from django.core.mail import send_mail
from django.contrib.postgres.search import TrigramSimilarity
from django.template.defaultfilters import slugify, truncatewords


now = datetime.now()


#обработчик страницы 404
def error_404_view(request, exception):
    popularvideo = CarVideo.objects.all().order_by('-number_of_views')
    popularvideo = popularvideo.filter(available=True)[:4]
    return render(request, '404.html', {'popularvideo': popularvideo,})


#обработчик страниц популярные видео
def head_page(request, brand_slug=None):
    brand = None
    brands = Brand.objects.all()
    car = None
    cars = Car.objects.filter(available=True)
    if brand_slug:
        brand = get_object_or_404(Brand, slug=brand_slug)
        cars = cars.filter(brand=brand)
    slug = None
    #получаем все видео из базы данных
    popularvideo = CarVideo.objects.all().order_by('-number_of_views')
    #если выбран бренд фильтруем
    if  brand_slug:
        popularvideo = popularvideo.filter(brand=brand, available=True)[:500]
    else:
        popularvideo = popularvideo.filter(available=True)[:4]
    newvideo = CarVideo.objects.all().order_by('-age')
    newvideo = newvideo.filter(available=True)[:4]

    posts = Post.published.all()[1:5]
    new_post = Post.published.all().order_by('-publish')[:1]

    return render(request, 'head/lists/head_page.html', {'new_post': new_post, 'posts': posts, 'brand': brand, 'brands': brands, 'cars': cars, 'car': car, 'popularvideo': popularvideo, 'slug': slug, 'now': now, 'newvideo': newvideo,})


#обработчик страниц популярные видео
def popular_list(request, brand_slug=None):
    brand = None
    brands = Brand.objects.all()
    car = None
    cars = Car.objects.filter(available=True)
    if brand_slug:
        brand = get_object_or_404(Brand, slug=brand_slug)
        cars = cars.filter(brand=brand)
    slug = 'popular_video/'
    #получаем все видео из базы данных
    popularvideo = CarVideo.objects.all().order_by('-number_of_views')
    #если выбран бренд фильтруем
    if  brand_slug:
        popularvideo = popularvideo.filter(brand=brand, available=True)[:500]
    else:
        popularvideo = popularvideo.filter(available=True)[:500]
    newvideo = CarVideo.objects.all().order_by('-age')
    newvideo = newvideo.filter(available=True)[:4]

    return render(request, 'head/lists/popular_video.html', {'slug': slug, 'brand': brand, 'brands': brands, 'cars': cars, 'car': car, 'popularvideo': popularvideo, 'slug': slug, 'now': now, 'newvideo': newvideo,})


#обработчик страницы новых видео
def new_video_list(request, brand_slug=None, car_slug=None):
    brand = None
    brands = Brand.objects.all()
    car = None
    cars = Car.objects.all()
    cars = Car.objects.filter(available=True)
    if brand_slug:
        brand = get_object_or_404(Brand, slug=brand_slug)
        cars = cars.filter(brand=brand)
    if car_slug:
        car = get_object_or_404(Car, slug=car_slug)
    slug = 'new_video/'

    newvideos = CarVideo.objects.all()
    newvideos = CarVideo.objects.all().order_by('-age')
    newvideos = newvideos.filter(available=True)[:500]
    popularvideo = CarVideo.objects.all().order_by('-number_of_views')
    popularvideo = popularvideo.filter(available=True)[:4]
    return render(request, 'head/lists/new_video.html', {'brands': brands, 'cars': cars, 'brand': brand, 'car': car, 'newvideos': newvideos, 'slug': slug, 'now': now, 'popularvideo': popularvideo,})


#обработчик страниц видео по брендам
def brand_list(request, brand_slug=None):
    brand = None
    brands = Brand.objects.all()
    car = None
    cars = Car.objects.filter(available=True)
    if brand_slug:
        brand = get_object_or_404(Brand, slug=brand_slug)
        cars = cars.filter(brand=brand)
    slug = brand_slug
    #получаем все видео из базы данных
    brandvideo = CarVideo.objects.all().order_by('-number_of_views')
    #если выбран бренд фильтруем
    if  brand_slug:
        brandvideo = brandvideo.filter(brand=brand, available=True)[:500]
    else:
        brandvideo = brandvideo.filter(available=True)[:500]
    newvideo = CarVideo.objects.all().order_by('-age')
    newvideo = newvideo.filter(available=True)[:4]

    return render(request, 'head/lists/brand_video.html', {'brand': brand, 'brands': brands, 'cars': cars, 'car': car, 'brandvideo': brandvideo, 'slug': slug, 'now': now, 'newvideo': newvideo,})


#обработчик страниц по моделям
def car_list(request, brand_slug=None, car_slug=None):
    brand = None
    brands = Brand.objects.all()
    car = None
    cars = Car.objects.all()
    cars = Car.objects.filter(available=True)
    if brand_slug:
        brand = get_object_or_404(Brand, slug=brand_slug)
        cars = cars.filter(brand=brand)
    if car_slug:
        car = get_object_or_404(Car, slug=car_slug)
    slug = car_slug
    # #фильтр за все время по количеству просмотров
    # filtr = '&sp=CAMSAhAB'
    # links, titles, number_of_views, image_urls, id_videos, hq, date, text_date = findyoutube('Тест драйв ' + str(brand) + str(car), filtr)
    # #Запись в модель CarVideo новых данных
    # save_video(titles, number_of_views, image_urls, id_videos, brand, car, hq, date, text_date)

    # #фильтр за все время по дате загрузки
    # filtr = '&sp=CAI%253D'
    # links, titles, number_of_views, image_urls, id_videos, hq, date, text_date = findyoutube('Тест драйв ' + str(brand) + str(car), filtr)
    # #Запись в модель CarVideo новых данных
    # save_video(titles, number_of_views, image_urls, id_videos, brand, car, hq, date, text_date)
                
    carvideo = CarVideo.objects.all().order_by('-number_of_views')
    carvideo = carvideo.filter(brand=brand, car=car, available=True)
    newvideo = CarVideo.objects.all().order_by('-age')
    newvideo = newvideo.filter(available=True)[:4]
    
    return render(request, 'head/lists/car_video.html', {'brands': brands, 'cars': cars, 'brand': brand, 'car': car, 'slug': slug, 'carvideo': carvideo, 'now': now, 'newvideo': newvideo,})


def post_list(request, tag_slug=None, brand_slug=None, car_slug=None):
    brand = None
    brands = Brand.objects.all()
    car = None
    cars = Car.objects.all()
    cars = Car.objects.filter(available=True)
    if brand_slug:
        brand = get_object_or_404(Brand, slug=brand_slug)
        cars = cars.filter(brand=brand)
    if car_slug:
        car = get_object_or_404(Car, slug=car_slug)

    object_list = Post.published.all()
    tag = None
    posts = Post.published.all()

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
        posts = object_list

    video = CarVideo.objects.all().order_by('-number_of_views')
    video = video.filter(available=True)[:4]
    slug = 'autonews/'
    return render(request, 'head/lists/posts.html', {'posts': posts, 'slug': slug, 'tag': tag, 'brands': brands, 'cars': cars, 'brand': brand, 'car': car, 'video': video, })

                  
def post_detail(request, year, month, post, brand_slug=None, car_slug=None,):
    brand = None
    brands = Brand.objects.all()
    car = None
    cars = Car.objects.all()
    cars = Car.objects.filter(available=True)
    if brand_slug:
        brand = get_object_or_404(Brand, slug=brand_slug)
        cars = cars.filter(brand=brand)
    if car_slug:
        car = get_object_or_404(Car, slug=car_slug)
    
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month)

    description = truncatewords(post.body, 30)

    # Список активных комментариев для этой статьи
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # Пользователь отправил комментарий
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Создаем комментарий, но пока не сохраняем в базе данных
            new_comment = comment_form.save(commit=False)
            # Привязываем комментарий к текущей статье
            new_comment.post = post
            # Сохраняем комментарий в базе данных
            new_comment.save()
    else:
        comment_form = CommentForm()

    # Формирование списка похожих статей
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    
    video = CarVideo.objects.all().order_by('-number_of_views')
    brand_name = post.brand
    slug_brand = str(brand_name).lower()
    video_brand = video.filter(brand=post.brand, available=True)[:4]
    video = video.filter(available=True)[:4]
    slug = post.slug

    return render(request, 'head/lists/post_detail.html',
                  {'post': post,
                   'slug': slug,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts, 
                   'brands': brands, 
                   'cars': cars, 
                   'brand': brand, 
                   'car': car, 
                   'brand_name': brand_name,
                   'slug_brand': slug_brand,
                   'video_brand': video_brand,
                   'video': video,
                   'description': description,
                   })


def post_share(request, post_id, brand_slug=None):
    brand = None
    brands = Brand.objects.all()

head/templates/head/lists/post_detail.html
{% extends "head/base.html" %}
{% load head_tags %}
{% load user_agents %}
{% load static %}
{% block title %}{{ post.title }}{% endblock %}
{% block description %} <meta name="Description" content="{{ post.description }}"/>{% endblock %}
{% block content %}
<h1>{{ post.title }}</h1>


{% if request|is_pc %}

  <div id="main" class="cars-list"> 
  <img class='img_post' src='{{ post.image_jpg.url }}'>
  <p>
    {{ post.body|safe }}
  </p>
  <p class="date">
    Источник motor1.com, 
    Опубликовано {{ post.publish }} 
  </p>

  <p>
    <a href='{% url "head:post_share" post.id %}'>Поделиться этой статьей</a>
  </p>
  {% if similar_posts %}
  <hr>
  <h2>Читайте также</h2>
  <div class="similar_posts">
  {% for post in similar_posts %}
  
      <a href="{{ post.get_absolute_url }}">
          <img class='sketch_img_post' src='{{ post.image_jpg.url }}'> 
        <p>{{ post.title }}</p>
      </a>
    
  {% endfor %}
  </div>
  {% endif %}
  <hr>
  {% with comments.count as total_comments %}
  
    <h2>{{ total_comments }} коммент. </h2>
  
  {% endwith %}
  {% for comment in comments %}
    <div class="comment">
      {{ comment.body|linebreaks }}
      <p class="info">
        {{ comment.name }} {{ comment.created }}
      </p>
    </div>
    {% empty %}
    <p>Еще нет ни одного комментария</p>
  {% endfor %}
  {% if new_comment %}
    <h2>Ваш комментарий был добавлен.</h2>
  {% else %}
    <h2>Добавить новый комментарий</h2>
    <form action="." method="post">
      {{ comment_form.as_p }}
      {% csrf_token %}
      <p><input type="submit" value="Отправить"></p>
    </form>
  {% endif %}

  <hr>
  <h3>
    {% if brand_name and video_brand %}
      <h3>Также смотрите видео обзоры {{ brand_name }}</h3>
      <div class="item">
        {% for v in video_brand %}
          <div class="imgvideo">
            <div class="video">
              <a class="newvideo_link" href="/{{ slug_brand }}/">
                <picture>
                  {% if v.image_webp_small %}
                    <source class="lazyload" data-src="{{ v.image_webp.url }}" data-srcset="{{ v.image_webp_small.url }} 400w, {{ v.image_webp.url }} 600w" sizes = "50vw" width="600" height="340" alt="{{ v.title_video }}">
                    <source class="lazyload" data-src="{{ v.image_jpg.url }}" data-srcset="{{ v.image_jpg.url }}" width="600" height="340" alt="{{ v.title_video }}">
                    <img class="lazyload" data-src="{{ v.image_jpg.url }}" width="100%" height="100%" alt="{{ v.title_video }}">
                  {% else %}
                    <source class="lazyload" data-src="{{ v.image_webp.url }}" data-srcset="{{ v.image_webp.url }}" width="600" height="340" alt="{{ v.title_video }}">
                    <source class="lazyload" data-src="{{ v.image_jpg.url }}" data-srcset="{{ v.image_jpg.url }}" width="600" height="340" alt="{{ v.title_video }}">
                    <img class="lazyload" data-src="{{ v.image_jpg.url }}" width="100%" height="100%" alt="{{ v.title_video }}">
                  {% endif %}
                </picture>
                <h4 class="link_to_newvideo">{{ v.title_video }}</h4>
              </a>
            </div>
          </div>
        {% endfor %}
        </div>

    {% else %}
      <h3>Также смотрите видео обзоры автомобилей</h3>
  <div class="item">
    {% for v in video %}
      <div class="imgvideo">
        <div class="video">
          <a class="newvideo_link" href="/">
            <picture>
              {% if v.image_webp_small %}
                <source class="lazyload" data-src="{{ v.image_webp.url }}" data-srcset="{{ v.image_webp_small.url }} 400w, {{ v.image_webp.url }} 600w" sizes = "50vw" width="600" height="340" alt="{{ v.title_video }}">
                <source class="lazyload" data-src="{{ v.image_jpg.url }}" data-srcset="{{ v.image_jpg.url }}" width="600" height="340" alt="{{ v.title_video }}">
                <img class="lazyload" data-src="{{ v.image_jpg.url }}" width="100%" height="100%" alt="{{ v.title_video }}">
              {% else %}
                <source class="lazyload" data-src="{{ v.image_webp.url }}" data-srcset="{{ v.image_webp.url }}" width="600" height="340" alt="{{ v.title_video }}">
                <source class="lazyload" data-src="{{ v.image_jpg.url }}" data-srcset="{{ v.image_jpg.url }}" width="600" height="340" alt="{{ v.title_video }}">
                <img class="lazyload" data-src="{{ v.image_jpg.url }}" width="100%" height="100%" alt="{{ v.title_video }}">
              {% endif %}
            </picture>
            <h4 class="link_to_newvideo">{{ v.title_video }}</h4>
          </a>
        </div>
      </div>
    {% endfor %}
    </div>
    {% endif %}
  </div>
{% endif %}

{% if request|is_mobile or request|is_tablet %}
<div id="m-main" class="cars-list"> 
  <img class='img_post' src='{{ post.image_jpg.url }}'>
  <p>
    {{ post.body|safe }}
  </p>
  <p class="date">
    Источник motor1.com, 
    Опубликовано {{ post.publish }} 
  </p>

  <p>
    <a href='{% url "head:post_share" post.id %}'>Поделиться этой статьей</a>
  </p>
  {% if similar_posts %}
  <hr>
  <h2>Читайте также</h2>
  <div class="similar_posts">
  {% for post in similar_posts %}
  
      <a href="{{ post.get_absolute_url }}">
          <img class='sketch_img_post' src='{{ post.image_jpg.url }}'> 
        <p>{{ post.title }}</p>
      </a>
    
  {% endfor %}
  </div>
  {% endif %}
  <hr>
  {% with comments.count as total_comments %}
  
    <h2>{{ total_comments }} коммент. </h2>
  
  {% endwith %}
  {% for comment in comments %}
    <div class="comment">
      {{ comment.body|linebreaks }}
      <p class="info">
        {{ comment.name }} {{ comment.created }}
      </p>
    </div>
    {% empty %}
    <p>Еще нет ни одного комментария</p>
  {% endfor %}
  {% if new_comment %}
    <h2>Ваш комментарий был добавлен.</h2>
  {% else %}
    <h2>Добавить новый комментарий</h2>
    <form action="." method="post">
      {{ comment_form.as_p }}
      {% csrf_token %}
      <p><input type="submit" value="Отправить"></p>
    </form>
  {% endif %}

  <hr>
  <h3>
    {% if brand_name and video_brand %}
      <h3>Также смотрите видео обзоры {{ brand_name }}</h3>
      <div class="item">
        {% for v in video_brand %}
          <div class="imgvideo">
            <div class="video">
              <a class="newvideo_link" href="/{{ slug_brand }}/">
                <picture>
                  {% if v.image_webp_small %}
                    <source class="lazyload" data-src="{{ v.image_webp.url }}" data-srcset="{{ v.image_webp_small.url }} 400w, {{ v.image_webp.url }} 600w" sizes = "50vw" width="600" height="340" alt="{{ v.title_video }}">
                    <source class="lazyload" data-src="{{ v.image_jpg.url }}" data-srcset="{{ v.image_jpg.url }}" width="600" height="340" alt="{{ v.title_video }}">
                    <img class="lazyload" data-src="{{ v.image_jpg.url }}" width="100%" height="100%" alt="{{ v.title_video }}">
                  {% else %}
                    <source class="lazyload" data-src="{{ v.image_webp.url }}" data-srcset="{{ v.image_webp.url }}" width="600" height="340" alt="{{ v.title_video }}">
                    <source class="lazyload" data-src="{{ v.image_jpg.url }}" data-srcset="{{ v.image_jpg.url }}" width="600" height="340" alt="{{ v.title_video }}">
                    <img class="lazyload" data-src="{{ v.image_jpg.url }}" width="100%" height="100%" alt="{{ v.title_video }}">
                  {% endif %}
                </picture>
                <h4 class="link_to_newvideo">{{ v.title_video }}</h4>
              </a>
            </div>
          </div>
        {% endfor %}
        </div>

    {% else %}
      <h3>Также смотрите видео обзоры автомобилей</h3>
  <div class="item">
    {% for v in video %}
      <div class="imgvideo">
        <div class="video">
          <a class="newvideo_link" href="/">
            <picture>
              {% if v.image_webp_small %}
                <source class="lazyload" data-src="{{ v.image_webp.url }}" data-srcset="{{ v.image_webp_small.url }} 400w, {{ v.image_webp.url }} 600w" sizes = "50vw" width="600" height="340" alt="{{ v.title_video }}">
                <source class="lazyload" data-src="{{ v.image_jpg.url }}" data-srcset="{{ v.image_jpg.url }}" width="600" height="340" alt="{{ v.title_video }}">
                <img class="lazyload" data-src="{{ v.image_jpg.url }}" width="100%" height="100%" alt="{{ v.title_video }}">
              {% else %}
                <source class="lazyload" data-src="{{ v.image_webp.url }}" data-srcset="{{ v.image_webp.url }}" width="600" height="340" alt="{{ v.title_video }}">
                <source class="lazyload" data-src="{{ v.image_jpg.url }}" data-srcset="{{ v.image_jpg.url }}" width="600" height="340" alt="{{ v.title_video }}">
                <img class="lazyload" data-src="{{ v.image_jpg.url }}" width="100%" height="100%" alt="{{ v.title_video }}">
              {% endif %}
            </picture>
            <h4 class="link_to_newvideo">{{ v.title_video }}</h4>
          </a>
        </div>
      </div>
    {% endfor %}
    </div>
    {% endif %}
</div>
{% endif %}

{% block extrahead %}
      <script async type="text/javascript" src="{% static 'js/lazyload.js' %}"></script>
      <script async type="text/javascript" src="{% static 'js/video.js' %}"></script>
      <script async type="text/javascript" src="{% static 'js/style.js' %}"></script>
{% endblock extrahead %}
{% endblock %}

head/templates/head/lists/share.html
{% extends "head/base.html" %}
{% load head_tags %}
{% load user_agents %}
{% load static %}
{% block title %}Поделиться новостью{% endblock %}

{% block content %}
<h1>Поделиться "{{ post.title }}" на e-mail</h1>
{% if request|is_pc %}
  
  <div id="main" class="cars-list"> 
  {% if sent %}
    <h1>E-mail успешно отправлено</h1>
    <p>
      "{{ post.title }}" отправлено {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <form action="." method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Отправить">
    </form>
  {% endif %}
  </div>
{% endif %}
{% endblock %}